//
// Copyright 2016 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-android v0.13
//
package com.amazonaws.mobile;

import com.amazonaws.regions.Regions;

/**
 * This class defines constants for the developer's resource
 * identifiers and API keys. This configuration should not
 * be shared or posted to any public source code repository.
 */
public class AWSConfiguration {
    // AWS MobileHub user agent string
    public static final String AWS_MOBILEHUB_USER_AGENT =
        "MobileHub 9f0a6131-d4ca-44bb-a238-fda5156ccc92 aws-my-sample-app-android-v0.13";
    // AMAZON COGNITO
    public static final Regions AMAZON_COGNITO_REGION =
      Regions.fromName("us-east-1");
    public static final String  AMAZON_COGNITO_IDENTITY_POOL_ID =
        "us-east-1:7c138bf6-4a02-41b3-a0c9-ff44e9eedbae";
    // AMAZON MOBILE ANALYTICS
    public static final String  AMAZON_MOBILE_ANALYTICS_APP_ID =
        "6df36a4096b24164a9d3764f46a98bd2";
    // Amazon Mobile Analytics region
    public static final Regions AMAZON_MOBILE_ANALYTICS_REGION = Regions.US_EAST_1;
    // S3 BUCKET
    public static final String AMAZON_S3_USER_FILES_BUCKET =
        "spotsurf-userfiles-mobilehub-353578097";
    // S3 BUCKET REGION
    public static final Regions AMAZON_S3_USER_FILES_BUCKET_REGION =
        Regions.fromName("us-east-1");
    public static final Regions AMAZON_DYNAMODB_REGION =
       Regions.fromName("us-east-1");
    public static final String AMAZON_COGNITO_USER_POOL_ID =
        "us-east-1_hd2AscWMI";
    public static final String AMAZON_COGNITO_USER_POOL_CLIENT_ID =
        "7nvc1c6pftt20qad7eski4v3kk";
    public static final String AMAZON_COGNITO_USER_POOL_CLIENT_SECRET =
        "1mfubm0o7gv37cpd883fudjidhg37l7n82kvajeod0r1bsukguk2";
}
